import type { User, Project, QAQuestion, ProfileQuestion } from '@/types';

export const CURRENT_USER_ID = 'user-derrick';

export const MOCK_USERS: User[] = [
  {
    id: 'user-derrick',
    name: 'Derrick Osei',
    username: 'derrick',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    bio: 'Building Scruttin. Interested in product development, startups, and internet businesses.',
    location: 'Uganda',
    expertise: ['Product development', 'Bootstrapping', 'SaaS', 'B2B'],
    acceptingQuestions: true,
    askTopics: ['Starting a business', 'Product development', 'Bootstrapping', 'Scruttin', 'Marketing'],
    projectIds: ['proj-scruttin', 'proj-payflow'],
    answeredQuestions: 38,
    articlesCount: 6,
    taggedCount: 12,
  },
  {
    id: 'user-amara',
    name: 'Amara Diallo',
    username: 'amara',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=80&h=80&fit=crop&crop=face',
    bio: 'Building Bakawa Coffee. Specialty coffee roaster from Accra. Learning everything about running a food business.',
    location: 'Ghana',
    expertise: ['Food business', 'Supply chain', 'Retail'],
    acceptingQuestions: true,
    askTopics: ['Running a food business', 'Sourcing suppliers', 'Pricing'],
    projectIds: ['proj-bakawa'],
    answeredQuestions: 14,
    articlesCount: 2,
    taggedCount: 8,
  },
  {
    id: 'user-kofi',
    name: 'Kofi Mensah',
    username: 'kofi',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    bio: 'Serial founder. 3 businesses, 1 exit. Now investing and advising early-stage founders in West Africa.',
    location: 'Nigeria',
    expertise: ['Fundraising', 'Operations', 'Hiring', 'Growth'],
    acceptingQuestions: true,
    askTopics: ['Fundraising', 'Team building', 'Operations', 'Exit strategy'],
    projectIds: ['proj-stacklabs'],
    answeredQuestions: 92,
    articlesCount: 14,
    taggedCount: 47,
  },
  {
    id: 'user-nina',
    name: 'Nina Okonkwo',
    username: 'nina',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    bio: 'Fashion tech founder. Building Stitchd — a marketplace connecting African designers with global buyers.',
    location: 'Lagos, Nigeria',
    expertise: ['Fashion', 'Marketplace', 'E-commerce'],
    acceptingQuestions: false,
    askTopics: [],
    projectIds: ['proj-stitchd'],
    answeredQuestions: 21,
    articlesCount: 5,
    taggedCount: 23,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-scruttin',
    name: 'Scruttin',
    logo: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=80&h=80&fit=crop',
    tagline: 'A social platform for people building businesses.',
    description: 'Scruttin connects founders, builders, and entrepreneurs through what they are building, what they know, and what they want to learn. Follow businesses as they grow, ask business questions, and learn from people with experience.',
    founderId: 'user-derrick',
    founderName: 'Derrick Osei',
    founderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    industry: 'SaaS',
    location: 'Uganda',
    website: 'scruttin.com',
    stage: 'Building',
    startedDate: 'Jan 2026',
    tagAlongCount: 1284,
    isTaggedAlong: false,
    lookingFor: ['Beta testers', 'Designer', 'Cofounder', 'Developer', 'Feedback'],
    updates: [
      {
        id: 'upd-1',
        projectId: 'proj-scruttin',
        projectName: 'Scruttin',
        projectLogo: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=80&h=80&fit=crop',
        type: 'Milestone',
        content: 'Passed 1,000 people tagging along 🎉 Still can\'t believe people are following this journey. Thank you to everyone who believes in what we\'re building.',
        authorName: 'Derrick Osei',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
        timestamp: '2 hours ago',
        likes: 84,
        comments: 17,
      },
      {
        id: 'upd-2',
        projectId: 'proj-scruttin',
        projectName: 'Scruttin',
        projectLogo: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=80&h=80&fit=crop',
        type: 'Decision',
        content: 'After a lot of back-and-forth, we\'ve decided not to build a DM system in V1. The risk of becoming a general social network is too high. Connections should happen through context — someone tags along, asks a question, answers something useful. That\'s enough.',
        authorName: 'Derrick Osei',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
        timestamp: '1 day ago',
        likes: 62,
        comments: 23,
      },
      {
        id: 'upd-3',
        projectId: 'proj-scruttin',
        projectName: 'Scruttin',
        projectLogo: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=80&h=80&fit=crop',
        type: 'Problem',
        content: 'Finding the right name was harder than expected. We went through 40+ names. Most were taken, some were just bad. Scruttin came from the word "scrutinize" — which is what founders do constantly. We\'re keeping it.',
        authorName: 'Derrick Osei',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
        timestamp: '3 days ago',
        likes: 41,
        comments: 28,
      },
    ],
    timeline: [
      { id: 't1', date: 'Jan 12', emoji: '💡', label: 'Idea started' },
      { id: 't2', date: 'Feb 3', emoji: '🔎', label: 'Customer interviews started' },
      { id: 't3', date: 'Mar 18', emoji: '🛠', label: 'First prototype built' },
      { id: 't4', date: 'Apr 7', emoji: '👤', label: 'First beta tester' },
      { id: 't5', date: 'Jun 2', emoji: '🚀', label: 'Soft launch' },
    ],
  },
  {
    id: 'proj-bakawa',
    name: 'Bakawa Coffee',
    logo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=80&h=80&fit=crop',
    tagline: 'Specialty coffee from source to cup, roasted in Accra.',
    description: 'Bakawa is a specialty coffee roasting business based in Accra, Ghana. We source directly from small farms across East and West Africa and roast on-site for wholesale and direct consumer orders.',
    founderId: 'user-amara',
    founderName: 'Amara Diallo',
    founderAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=80&h=80&fit=crop&crop=face',
    industry: 'Food & Beverage',
    location: 'Accra, Ghana',
    website: 'bakawacoffee.com',
    stage: 'Growing',
    startedDate: 'Mar 2024',
    tagAlongCount: 847,
    isTaggedAlong: true,
    lookingFor: ['Suppliers', 'Marketing help', 'Investors'],
    updates: [
      {
        id: 'upd-b1',
        projectId: 'proj-bakawa',
        projectName: 'Bakawa Coffee',
        projectLogo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=80&h=80&fit=crop',
        type: 'Update',
        content: 'Just signed our third wholesale account — a hotel group here in Accra. Small step, but it validates that the hospitality sector is the right first B2B channel.',
        authorName: 'Amara Diallo',
        authorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=80&h=80&fit=crop&crop=face',
        timestamp: '4 hours ago',
        likes: 56,
        comments: 8,
      },
      {
        id: 'upd-b2',
        projectId: 'proj-bakawa',
        projectName: 'Bakawa Coffee',
        projectLogo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=80&h=80&fit=crop',
        type: 'Lesson',
        content: 'We priced ourselves 40% below what the market could actually bear. We were afraid. Raised prices last month and didn\'t lose a single customer. Price based on your value, not your fear.',
        authorName: 'Amara Diallo',
        authorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=80&h=80&fit=crop&crop=face',
        timestamp: '2 days ago',
        likes: 113,
        comments: 31,
      },
    ],
    timeline: [
      { id: 't1', date: 'Mar 2024', emoji: '💡', label: 'Idea started' },
      { id: 't2', date: 'May 2024', emoji: '🔎', label: 'First sourcing trip' },
      { id: 't3', date: 'Aug 2024', emoji: '🛠', label: 'First roast batch' },
      { id: 't4', date: 'Sep 2024', emoji: '💰', label: 'First sale' },
      { id: 't5', date: 'Jan 2025', emoji: '🚀', label: 'Wholesale launch' },
    ],
  },
  {
    id: 'proj-stitchd',
    name: 'Stitchd',
    logo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=80&h=80&fit=crop',
    tagline: 'Connecting African designers with global buyers.',
    description: 'A curated marketplace bringing together independent fashion designers from across Africa with buyers in the US, UK, and Europe. We handle logistics, payments, and brand storytelling.',
    founderId: 'user-nina',
    founderName: 'Nina Okonkwo',
    founderAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    industry: 'Fashion',
    location: 'Lagos, Nigeria',
    website: 'stitchd.co',
    stage: 'Launched',
    startedDate: 'Sep 2025',
    tagAlongCount: 2103,
    isTaggedAlong: false,
    lookingFor: ['Investors', 'Marketing help', 'Beta testers'],
    updates: [
      {
        id: 'upd-s1',
        projectId: 'proj-stitchd',
        projectName: 'Stitchd',
        projectLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=80&h=80&fit=crop',
        type: 'Launch',
        content: 'We\'re officially live 🚀 42 designers from 9 countries. Buyers can now discover and order directly. This took 18 months. A lot of it was ugly. All of it was worth it.',
        authorName: 'Nina Okonkwo',
        authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
        timestamp: '1 week ago',
        likes: 284,
        comments: 67,
      },
    ],
    timeline: [
      { id: 't1', date: 'Sep 2025', emoji: '💡', label: 'Concept started' },
      { id: 't2', date: 'Nov 2025', emoji: '🔎', label: 'Designer outreach' },
      { id: 't3', date: 'Feb 2026', emoji: '🛠', label: 'Platform development' },
      { id: 't4', date: 'Jun 2026', emoji: '👤', label: 'First designer onboarded' },
      { id: 't5', date: 'Aug 2026', emoji: '🚀', label: 'Public launch' },
    ],
  },
  {
    id: 'proj-stacklabs',
    name: 'StackLabs',
    logo: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=80&h=80&fit=crop',
    tagline: 'No-code tools for African SMEs.',
    description: 'We build no-code workflow automation tools specifically designed for the constraints of small and medium businesses in Africa — offline support, mobile-first, and local payment integrations.',
    founderId: 'user-kofi',
    founderName: 'Kofi Mensah',
    founderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    industry: 'Technology',
    location: 'Nigeria',
    website: 'stacklabs.africa',
    stage: 'Validating',
    startedDate: 'Jul 2026',
    tagAlongCount: 391,
    isTaggedAlong: false,
    lookingFor: ['Beta testers', 'Feedback', 'Cofounder'],
    updates: [
      {
        id: 'upd-k1',
        projectId: 'proj-stacklabs',
        projectName: 'StackLabs',
        projectLogo: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=80&h=80&fit=crop',
        type: 'Ask',
        content: 'Has anyone successfully sold B2B SaaS to SMEs in West Africa via WhatsApp? Not looking for a technology answer — the technology is fine. Looking for a sales motion answer.',
        authorName: 'Kofi Mensah',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
        timestamp: '6 hours ago',
        likes: 24,
        comments: 14,
      },
    ],
    timeline: [
      { id: 't1', date: 'Jul 2026', emoji: '💡', label: 'Idea started' },
      { id: 't2', date: 'Aug 2026', emoji: '🔎', label: 'Market research' },
    ],
  },
  {
    id: 'proj-payflow',
    name: 'PayFlow',
    logo: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=80&h=80&fit=crop',
    tagline: 'Simple invoicing and payments for African freelancers.',
    description: 'PayFlow helps African freelancers and agencies send professional invoices, collect payments in multiple currencies, and track what they\'re owed.',
    founderId: 'user-derrick',
    founderName: 'Derrick Osei',
    founderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    industry: 'Finance',
    location: 'Uganda',
    stage: 'Idea',
    startedDate: 'Sep 2026',
    tagAlongCount: 126,
    isTaggedAlong: false,
    lookingFor: ['Feedback', 'Beta testers'],
    updates: [
      {
        id: 'upd-p1',
        projectId: 'proj-payflow',
        projectName: 'PayFlow',
        projectLogo: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=80&h=80&fit=crop',
        type: 'Update',
        content: 'Just starting to think about this. Had a terrible experience getting paid for a project last month — took 6 weeks and 3 different payment methods. There has to be a better way.',
        authorName: 'Derrick Osei',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
        timestamp: '2 days ago',
        likes: 18,
        comments: 6,
      },
    ],
    timeline: [
      { id: 't1', date: 'Sep 2026', emoji: '💡', label: 'Idea started' },
    ],
  },
];

export const QA_CATEGORIES = [
  'Starting', 'Ideas', 'Validation', 'Customers', 'Sales',
  'Marketing', 'Pricing', 'Money', 'Funding', 'Product',
  'Hiring', 'Operations', 'Legal', 'Leadership', 'Failure', 'Growth'
];

export const MOCK_QA: QAQuestion[] = [
  {
    id: 'qa-1',
    question: 'How did you get your first ten customers?',
    askedBy: 'Sarah K.',
    askedByAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=40&h=40&fit=crop&crop=face',
    category: 'Customers',
    timestamp: '3 hours ago',
    votes: 47,
    answers: [
      {
        id: 'ans-1a',
        questionId: 'qa-1',
        authorId: 'user-amara',
        authorName: 'Amara Diallo',
        authorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=40&h=40&fit=crop&crop=face',
        authorProject: 'Bakawa Coffee',
        type: 'voice',
        content: 'Shared how I landed first customers by personally delivering samples to cafes and hotel lobbies every Saturday for 6 weeks.',
        duration: '1:47',
        timestamp: '2 hours ago',
        votes: 31,
      },
      {
        id: 'ans-1b',
        questionId: 'qa-1',
        authorId: 'user-kofi',
        authorName: 'Kofi Mensah',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face',
        authorProject: 'StackLabs',
        type: 'text',
        content: 'My first 10 customers all came from one WhatsApp group. I posted a genuine question about a problem I was solving, not a pitch. Three people replied asking if I had a solution. That turned into five paying customers within a week, and they each referred one or two more. Don\'t pitch, solve. Then tell people you solved it.',
        timestamp: '1 hour ago',
        votes: 28,
      },
    ],
  },
  {
    id: 'qa-2',
    question: 'When should a small business start hiring?',
    askedBy: 'Marcus T.',
    askedByAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face',
    category: 'Hiring',
    timestamp: '5 hours ago',
    votes: 34,
    answers: [
      {
        id: 'ans-2a',
        questionId: 'qa-2',
        authorId: 'user-kofi',
        authorName: 'Kofi Mensah',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face',
        authorProject: 'StackLabs',
        type: 'voice',
        content: 'Talked about the "pain test" — hire when the cost of not hiring is greater than the cost of hiring. Shared a story about waiting too long and losing a client.',
        duration: '2:14',
        timestamp: '4 hours ago',
        votes: 22,
      },
    ],
  },
  {
    id: 'qa-3',
    question: 'How do you know when your idea isn\'t working?',
    askedBy: 'Priya M.',
    askedByAvatar: 'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=40&h=40&fit=crop&crop=face',
    category: 'Validation',
    timestamp: '1 day ago',
    votes: 89,
    answers: [
      {
        id: 'ans-3a',
        questionId: 'qa-3',
        authorId: 'user-derrick',
        authorName: 'Derrick Osei',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face',
        authorProject: 'Scruttin',
        type: 'text',
        content: 'The clearest signal I\'ve found: people say "that\'s a great idea" but won\'t pre-pay, give their email, or do the next step you ask them to do. Enthusiasm without action is noise. I had 60 people tell me my first startup idea was brilliant. Zero of them signed up for the waitlist I sent two days later. That\'s the signal.',
        timestamp: '22 hours ago',
        votes: 64,
      },
    ],
  },
  {
    id: 'qa-4',
    question: 'Should I charge monthly or per transaction for a marketplace?',
    askedBy: 'Yemi A.',
    askedByAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face',
    category: 'Pricing',
    timestamp: '2 days ago',
    votes: 56,
    answers: [
      {
        id: 'ans-4a',
        questionId: 'qa-4',
        authorId: 'user-nina',
        authorName: 'Nina Okonkwo',
        authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face',
        authorProject: 'Stitchd',
        type: 'voice',
        content: 'Explained why we chose transaction fees over subscriptions for Stitchd, and what changed after launch.',
        duration: '3:02',
        timestamp: '1 day ago',
        votes: 41,
      },
    ],
  },
  {
    id: 'qa-5',
    question: 'What\'s something you wish you knew before opening a food business?',
    askedBy: 'Daniel O.',
    askedByAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=40&h=40&fit=crop&crop=face',
    category: 'Starting',
    timestamp: '3 days ago',
    votes: 72,
    answers: [
      {
        id: 'ans-5a',
        questionId: 'qa-5',
        authorId: 'user-amara',
        authorName: 'Amara Diallo',
        authorAvatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=40&h=40&fit=crop&crop=face',
        authorProject: 'Bakawa Coffee',
        type: 'voice',
        content: 'The real cost breakdown nobody tells you, from licensing to spoilage to equipment maintenance.',
        duration: '4:31',
        timestamp: '2 days ago',
        votes: 58,
      },
    ],
  },
];

export const MOCK_PROFILE_QUESTIONS: ProfileQuestion[] = [
  {
    id: 'pq-1',
    toUserId: 'user-derrick',
    fromName: 'James O.',
    question: 'Why did you decide to build Scruttin?',
    isAnswered: true,
    answer: {
      type: 'text',
      content: 'I kept seeing founders on Twitter or LinkedIn but only when they were winning. Nobody shares the messy middle — the weeks where nothing works, the decisions that go wrong, the pivots. I wanted a place where the messy middle was actually the product. The journey is more interesting than the highlight reel.',
    },
    timestamp: '2 weeks ago',
    isPublic: true,
  },
  {
    id: 'pq-2',
    toUserId: 'user-derrick',
    fromName: 'Anonymous',
    question: 'How do you balance building Scruttin with PayFlow?',
    isAnswered: true,
    answer: {
      type: 'voice',
      content: 'Shared my week structure and why I treat them as separate mental contexts, not competing priorities.',
      duration: '2:08',
    },
    timestamp: '4 days ago',
    isPublic: true,
  },
  {
    id: 'pq-3',
    toUserId: 'user-derrick',
    fromName: 'Fatou B.',
    question: 'Did you consider raising investment for Scruttin?',
    isAnswered: false,
    timestamp: '1 day ago',
    isPublic: false,
  },
];

export const STAGE_COLORS: Record<string, string> = {
  Idea: 'bg-purple-100 text-purple-700',
  Validating: 'bg-blue-100 text-blue-700',
  Building: 'bg-amber-100 text-amber-700',
  Testing: 'bg-cyan-100 text-cyan-700',
  Launched: 'bg-green-100 text-green-700',
  Growing: 'bg-emerald-100 text-emerald-800',
};

export const UPDATE_TYPE_STYLES: Record<string, { color: string; bg: string; emoji: string }> = {
  Update: { color: 'text-slate-600', bg: 'bg-slate-100', emoji: '📢' },
  Problem: { color: 'text-red-600', bg: 'bg-red-50', emoji: '🔴' },
  Decision: { color: 'text-blue-600', bg: 'bg-blue-50', emoji: '🔵' },
  Ask: { color: 'text-purple-600', bg: 'bg-purple-50', emoji: '❓' },
  Milestone: { color: 'text-amber-600', bg: 'bg-amber-50', emoji: '🏆' },
  Lesson: { color: 'text-teal-600', bg: 'bg-teal-50', emoji: '💡' },
  Launch: { color: 'text-green-600', bg: 'bg-green-50', emoji: '🚀' },
};
